stages:
  - test
  - build
  - deploy

unit_test:
  stage: test
  image: node:16.20.2
  script:
    - npm install
    - npm run test


deploy:
  stage: deploy
  image: valudio/docker-sshpass:latest
  script:
    - sshpass -p $PASS ssh user@$SERVER -t -o StrictHostKeychecking=no env HD=/home/user/tmp UN=user HOST=api.domain.com APIURI=graphql VERSION=main APP_HOST=dashboard.domain.com APP_MOUNT_URI=app.domain.com 'bash -s' < deploy/deploy.sh